#!/usr/bin/env python3
"""Exercise synchronization and both sides of the sealed release-patch boundary."""

from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import sync_python_version as sync


VALIDATOR = Path(__file__).with_name("validate-version-changes.py").resolve()
SYNC_SCRIPT = Path(sync.__file__).resolve()
OLD = "0.3.0"
NEW = "0.3.1"


def manifest(name: str, version: str) -> str:
    return f'[package]\nname = "{name}"\nversion = "{version}" # keep this comment\n'


def wheel_manifest(version: str) -> str:
    return manifest("tellegen-py", version) + '''publish = false

[dependencies]
tellegen = { path = "../tellegen" }

[package.metadata]
version = "unchanged"
'''


def lock(engine: str, wheel: str) -> str:
    return f'''# Generated by Cargo. Preserve the rest of this file byte for byte.
version = 4

[[package]]
name = "tellegen"
version = "{engine}"

[[package]]
name = "tellegen-py"
version = "{wheel}"
dependencies = [
 "tellegen",
]
'''


def write(root: Path, path: Path | str, text: str) -> None:
    target = root / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)


def git(root: Path, *args: str) -> bytes:
    return subprocess.check_output(["git", *args], cwd=root, stderr=subprocess.PIPE)


class VersionSyncTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        write(self.root, sync.ENGINE_MANIFEST, manifest("tellegen", NEW))
        write(self.root, sync.PYTHON_MANIFEST, wheel_manifest(OLD))
        write(self.root, sync.LOCKFILE, lock(NEW, OLD))

    def test_only_versions_change_and_repeated_run_is_noop(self) -> None:
        sync.synchronize(self.root)
        self.assertEqual((self.root / sync.PYTHON_MANIFEST).read_text(), wheel_manifest(NEW))
        self.assertEqual((self.root / sync.LOCKFILE).read_text(), lock(NEW, NEW))
        paths = [self.root / path for path in (sync.PYTHON_MANIFEST, sync.LOCKFILE)]
        modified = [path.stat().st_mtime_ns for path in paths]
        sync.synchronize(self.root)
        self.assertEqual(modified, [path.stat().st_mtime_ns for path in paths])

    def test_prerelease_and_quoted_version_preserve_other_fields(self) -> None:
        version = "1.0.0-rc.1+build.2"
        write(self.root, sync.ENGINE_MANIFEST, manifest("tellegen", version))
        write(self.root, sync.LOCKFILE, lock(version, OLD))
        text = wheel_manifest(OLD).replace('"0.3.0"', "'0.3.0'")
        write(self.root, sync.PYTHON_MANIFEST, text)
        sync.synchronize(self.root)
        self.assertEqual(
            (self.root / sync.PYTHON_MANIFEST).read_text(), text.replace(OLD, version)
        )

    def test_invalid_lock_never_partially_writes_manifest(self) -> None:
        invalid_locks = [
            lock(OLD, OLD),
            lock(NEW, "0.2.0"),
            lock(NEW, OLD) + '\n[[package]]\nname = "tellegen-py"\nversion = "0.3.0"\n',
            lock(NEW, OLD).replace('name = "tellegen-py"', 'name = "another-crate"'),
            lock(NEW, OLD) + 'source = "registry+https://example.invalid"\n',
            lock(NEW, OLD) + 'checksum = "unexpected"\n',
            "invalid TOML",
        ]
        for invalid in invalid_locks:
            with self.subTest(lock=invalid):
                write(self.root, sync.LOCKFILE, invalid)
                with self.assertRaises(SystemExit):
                    sync.synchronize(self.root)
                self.assertEqual((self.root / sync.PYTHON_MANIFEST).read_text(), wheel_manifest(OLD))
                self.assertEqual((self.root / sync.LOCKFILE).read_text(), invalid)

    def test_unexpected_manifest_and_nonregular_files_are_rejected(self) -> None:
        path = self.root / sync.PYTHON_MANIFEST
        for invalid in (
            wheel_manifest(OLD).replace('name = "tellegen-py"', 'name = "other"'),
            wheel_manifest(OLD).replace('version = "0.3.0"', 'version.workspace = true'),
        ):
            path.write_text(invalid)
            with self.assertRaises(SystemExit):
                sync.synchronize(self.root)
            self.assertEqual(path.read_text(), invalid)
        path.write_text(wheel_manifest(OLD))
        path.chmod(0o755)
        with self.assertRaises(SystemExit):
            sync.synchronize(self.root)
        path.chmod(0o644)
        saved = self.root / "original-manifest"
        path.rename(saved)
        path.symlink_to(saved)
        with self.assertRaises(SystemExit):
            sync.synchronize(self.root)
        self.assertEqual(saved.read_text(), wheel_manifest(OLD))


class ReleasePatchTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        write(self.root, sync.ENGINE_MANIFEST, manifest("tellegen", OLD))
        write(self.root, sync.PYTHON_MANIFEST, wheel_manifest(OLD))
        write(self.root, sync.LOCKFILE, lock(OLD, OLD))
        write(self.root, "crates/tellegen/CHANGELOG.md", "# Changelog\n")
        git(self.root, "init", "--quiet")
        git(self.root, "config", "user.name", "Release test")
        git(self.root, "config", "user.email", "release-test@example.invalid")
        git(self.root, "add", ".")
        git(self.root, "-c", "core.hooksPath=/dev/null", "commit", "--quiet", "-m", "Baseline")

    def generate(self) -> None:
        write(self.root, sync.ENGINE_MANIFEST, manifest("tellegen", NEW))
        write(self.root, sync.LOCKFILE, lock(NEW, OLD))
        write(self.root, "crates/tellegen/CHANGELOG.md", "# Changelog\n\n## 0.3.1\n")
        subprocess.check_call([sys.executable, str(SYNC_SCRIPT)], cwd=self.root)

    def validate(self, valid: bool = True, root: Path | None = None) -> None:
        result = subprocess.run(
            [sys.executable, str(VALIDATOR), "crate"], cwd=root or self.root,
            text=True, capture_output=True,
        )
        if valid:
            self.assertEqual(result.returncode, 0, result.stderr)
        else:
            self.assertNotEqual(result.returncode, 0, "invalid release patch was accepted")

    def test_generate_seal_and_apply_on_fresh_checkout(self) -> None:
        self.generate()
        self.validate()
        patch = git(self.root, "diff", "--binary", "--full-index", "--no-ext-diff")
        with tempfile.TemporaryDirectory() as directory:
            fresh = Path(directory) / "checkout"
            git(self.root, "clone", "--quiet", "--no-hardlinks", str(self.root), str(fresh))
            subprocess.run(
                ["git", "apply", "--index", "--binary", "-"], cwd=fresh,
                input=patch, check=True,
            )
            self.validate(root=fresh)
        git(self.root, "add", ".")
        self.validate()

    def test_no_release_update_is_a_noop(self) -> None:
        subprocess.check_call([sys.executable, str(SYNC_SCRIPT)], cwd=self.root)
        self.assertEqual(git(self.root, "status", "--porcelain"), b"")
        self.validate(valid=False)  # The workflow skips sealing this empty patch.

    def test_already_synchronized_wheel_does_not_require_a_fourth_change(self) -> None:
        write(self.root, sync.PYTHON_MANIFEST, wheel_manifest(NEW))
        write(self.root, sync.LOCKFILE, lock(OLD, NEW))
        git(self.root, "add", ".")
        git(self.root, "-c", "core.hooksPath=/dev/null", "commit", "--quiet", "-m", "Prealigned wheel")
        write(self.root, sync.ENGINE_MANIFEST, manifest("tellegen", NEW))
        write(self.root, sync.LOCKFILE, lock(NEW, NEW))
        write(self.root, "crates/tellegen/CHANGELOG.md", "# Changelog\n\n## 0.3.1\n")
        subprocess.check_call([sys.executable, str(SYNC_SCRIPT)], cwd=self.root)
        self.validate()
        git(self.root, "add", ".")
        self.validate()

    def test_unsynchronized_manifest_or_lock_is_rejected(self) -> None:
        self.generate()
        write(self.root, sync.PYTHON_MANIFEST, wheel_manifest(OLD))
        self.validate(valid=False)
        write(self.root, sync.PYTHON_MANIFEST, wheel_manifest(NEW))
        for invalid in (lock(NEW, OLD), lock(OLD, NEW)):
            write(self.root, sync.LOCKFILE, invalid)
            self.validate(valid=False)

    def test_python_changes_are_strictly_version_only(self) -> None:
        self.generate()
        invalid_manifests = [
            wheel_manifest(NEW) + "\n# Unrelated edit\n",
            wheel_manifest(NEW).replace('path = "../tellegen"', 'path = "../other"'),
            wheel_manifest(NEW).replace("publish = false", "publish = true"),
            wheel_manifest(NEW).replace('version = "unchanged"', 'version = "changed"'),
            wheel_manifest(NEW).replace("\n", "\r\n"),
        ]
        for manifest in invalid_manifests:
            for staged in (False, True):
                with self.subTest(manifest=manifest, staged=staged):
                    git(self.root, "reset", "--quiet")
                    write(self.root, sync.PYTHON_MANIFEST, manifest)
                    if staged:
                        git(self.root, "add", ".")
                    self.validate(valid=False)

    def test_extra_path_and_missing_release_output_are_rejected(self) -> None:
        self.generate()
        write(self.root, "unexpected", "not a release file\n")
        self.validate(valid=False)
        (self.root / "unexpected").unlink()
        git(self.root, "checkout", "--", "crates/tellegen/CHANGELOG.md")
        self.validate(valid=False)

    def test_executable_symlink_and_deleted_python_manifest_are_rejected(self) -> None:
        self.generate()
        path = self.root / sync.PYTHON_MANIFEST
        path.chmod(0o755)
        self.validate(valid=False)
        path.chmod(0o644)
        path.unlink()
        path.symlink_to("../tellegen/Cargo.toml")
        self.validate(valid=False)
        path.unlink()
        self.validate(valid=False)


if __name__ == "__main__":
    unittest.main()
