//! Numerical regression for the supported voltage-dependent load laws.
//!
//! The 56 small cases are generated by `generate_mc_load_oracle.py` with
//! OpenDSSDirect.py 0.9.4.  They use an ideal source and disable the OpenDSS
//! voltage-band fallbacks, so the report is an equation-level reference for
//! the PowerIO models rather than a claim about a default OpenDSS run.

#![cfg(feature = "mc-pf")]

use serde::Deserialize;
use std::{
    fs,
    path::{Path, PathBuf},
};
use tellegen::{solve_bmopf_json, McPfOptions, McPfResult};

#[derive(Deserialize)]
struct Report {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    case: String,
    voltage: Complex,
    current: Complex,
    power: Complex,
}

#[derive(Clone, Copy, Debug, Deserialize)]
struct Complex {
    re: f64,
    im: f64,
}

impl Complex {
    fn norm(self) -> f64 {
        self.re.hypot(self.im)
    }
}

fn distance(a: Complex, b: Complex) -> f64 {
    (a.re - b.re).hypot(a.im - b.im)
}

fn run_case(case: &Case, data_dir: &Path) {
    let input_path = data_dir.join(format!("{}.json", case.case));
    let input = fs::read_to_string(&input_path).unwrap_or_else(|error| {
        panic!(
            "{}: cannot read {}: {error}",
            case.case,
            input_path.display()
        )
    });
    let raw: serde_json::Value = serde_json::from_str(&input).expect("valid oracle input");
    let load_bus = raw["load"]["ld"]["bus"].as_str().expect("load bus");
    let resistance = if load_bus == "lb" { 0.7 } else { 0.0 };

    let result: McPfResult = serde_json::from_str(
        &solve_bmopf_json(&input, &McPfOptions::default())
            .unwrap_or_else(|error| panic!("{}: {error}", case.case)),
    )
    .expect("serialized MC PF result");
    assert!(result.converged, "{} did not converge", case.case);
    assert_eq!(
        result.factorization_count,
        usize::from(resistance > 0.0),
        "{} LU reuse contract",
        case.case
    );

    let voltage = result
        .terminals
        .iter()
        .find(|terminal| terminal.bus == load_bus && terminal.terminal == "a")
        .unwrap_or_else(|| panic!("{}: missing {load_bus}.a", case.case))
        .voltage;
    let voltage = Complex {
        re: voltage.re,
        im: voltage.im,
    };
    let actual_current = result
        .element_ports
        .iter()
        .filter(|port| port.element == "ld" && port.bus == load_bus && port.terminal == "a")
        .map(|port| Complex {
            re: port.current_into_element.re,
            im: port.current_into_element.im,
        })
        .fold(Complex { re: 0.0, im: 0.0 }, |a, b| Complex {
            re: a.re + b.re,
            im: a.im + b.im,
        });
    let actual_power = result
        .element_ports
        .iter()
        .filter(|port| port.element == "ld" && port.bus == load_bus && port.terminal == "a")
        .map(|port| Complex {
            re: port.power_into_element.re,
            im: port.power_into_element.im,
        })
        .fold(Complex { re: 0.0, im: 0.0 }, |a, b| Complex {
            re: a.re + b.re,
            im: a.im + b.im,
        });

    let voltage_error = distance(voltage, case.voltage);
    assert!(
        voltage_error <= 1e-5,
        "{} voltage error {voltage_error:.3e} V",
        case.case
    );
    let current_error = distance(actual_current, case.current);
    assert!(
        current_error <= 2e-6 + 1e-7 * case.current.norm(),
        "{} current error {current_error:.3e} A",
        case.case
    );
    let power_error = distance(actual_power, case.power);
    assert!(
        power_error <= 1e-3 + 1e-7 * case.power.norm(),
        "{} load power error {power_error:.3e} VA",
        case.case
    );
}

#[test]
fn supported_load_models_match_frozen_equation_oracle() {
    let data_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data/mc_load_oracle");
    let report: Report = serde_json::from_str(
        &fs::read_to_string(data_dir.join("report.json")).expect("oracle report"),
    )
    .expect("valid oracle report");
    assert_eq!(report.cases.len(), 56, "oracle coverage changed");
    for case in &report.cases {
        run_case(case, &data_dir);
    }
}
