//! Frozen small-system numerical checks against OpenDSSDirect.py 0.9.4.
//!
//! References are generated by `generate_mc_pf_oracle.py` from the
//! BMOPFTools.jl comparison snapshots at commit 8ca84ab.  The oracle uses
//! the strict ideal-source/constant-power profile documented in each fixture;
//! it is deliberately not a claim about a default OpenDSS finite-source run.

#![cfg(feature = "mc-pf")]

use serde::Deserialize;
use std::collections::BTreeMap;
use tellegen::{solve_bmopf_json, McPfOptions, McPfResult};

#[derive(Deserialize)]
struct Oracle {
    terminals: Vec<OracleTerminal>,
    elements: Vec<OracleElement>,
}

#[derive(Deserialize)]
struct OracleTerminal {
    bus: String,
    terminal: String,
    voltage: Complex,
}

#[derive(Deserialize)]
struct OracleElement {
    name: String,
    node_order: Vec<OracleNodeOrder>,
    num_conductors: usize,
    currents: Vec<Complex>,
    powers: Vec<Complex>,
}

#[derive(Deserialize)]
struct OracleNodeOrder {
    bus: String,
    nodes: Vec<u8>,
}

#[derive(Deserialize)]
struct Complex {
    re: f64,
    im: f64,
}

fn run(case: &str, input: &str, reference: &str) {
    let result: McPfResult =
        serde_json::from_str(&solve_bmopf_json(input, &McPfOptions::default()).unwrap()).unwrap();
    assert!(result.converged, "{case} did not converge: {result:?}");
    assert_eq!(result.factorization_count, 1, "{case} must retain one LU");
    let oracle: Oracle = serde_json::from_str(reference).unwrap();
    let actual: BTreeMap<_, _> = result
        .terminals
        .iter()
        .map(|terminal| {
            (
                (terminal.bus.as_str(), terminal.terminal.as_str()),
                terminal,
            )
        })
        .collect();
    assert_eq!(
        actual.len(),
        oracle.terminals.len(),
        "{case} node coverage changed"
    );
    let mut max_error: f64 = 0.0;
    for expected in &oracle.terminals {
        let actual = actual
            .get(&(expected.bus.as_str(), expected.terminal.as_str()))
            .unwrap_or_else(|| panic!("{case} is missing {}:{}", expected.bus, expected.terminal));
        let error = ((actual.voltage.re - expected.voltage.re).powi(2)
            + (actual.voltage.im - expected.voltage.im).powi(2))
        .sqrt();
        max_error = max_error.max(error);
    }
    // The pinned ideal-source OpenDSS model uses a 1e-12 pu source impedance;
    // this leaves a tiny source drop at high-current terminals.
    assert!(max_error < 1e-5, "{case} voltage error {max_error:.3e} V");

    let port_names: BTreeMap<_, _> = result
        .element_ports
        .iter()
        .map(|port| (port.element.as_str(), ()))
        .collect();
    for expected in oracle
        .elements
        .iter()
        .filter(|element| !element.name.starts_with("Vsource."))
    {
        let short_name = expected
            .name
            .split_once('.')
            .map_or(expected.name.as_str(), |(_, name)| name);
        assert!(
            port_names.contains_key(short_name),
            "{case} has no ports for {short_name}"
        );
        // Ground reactors remain finite shunts in the circuit, but this oracle
        // comparison excludes their boundary-reaction current convention.
        // OpenDSS transformer winding vectors include padded/implicit
        // conductors and a winding convention that is not the canonical
        // BMOPF port convention. Their solver ports are still required and
        // checked for finite values; line/load ports use numeric comparison.
        if expected.name.starts_with("Reactor.") || expected.name.starts_with("Transformer.") {
            assert!(
                actual_ports_are_finite(&result, short_name),
                "{case} non-finite {short_name} ports"
            );
            continue;
        }
        let actual_ports: Vec<_> = result
            .element_ports
            .iter()
            .filter(|port| port.element == short_name)
            .collect();
        for (bus_index, bus) in expected.node_order.iter().enumerate() {
            let bus_name = bus.bus.as_str();
            assert_eq!(
                bus.nodes.len(),
                expected.num_conductors,
                "{case} {short_name} oracle node-order width"
            );
            for (conductor, node) in bus.nodes.iter().enumerate() {
                let terminal = match *node {
                    1 => "a",
                    2 => "b",
                    3 => "c",
                    4 | 0 => "n",
                    other => panic!("unsupported oracle conductor node {other}"),
                };
                let actual: Complex = actual_ports
                    .iter()
                    .filter(|port| port.bus == bus_name && port.terminal == terminal)
                    .map(|port| port.current_into_element)
                    .fold(Complex { re: 0.0, im: 0.0 }, |sum, value| Complex {
                        re: sum.re + value.re,
                        im: sum.im + value.im,
                    });
                let has_actual = actual_ports
                    .iter()
                    .any(|port| port.bus == bus_name && port.terminal == terminal);
                assert!(
                    has_actual,
                    "{case} missing {short_name} port {bus_name}.{terminal}"
                );
                let expected_current =
                    &expected.currents[bus_index * expected.num_conductors + conductor];
                let error =
                    (actual.re - expected_current.re).hypot(actual.im - expected_current.im);
                let scale = expected_current.re.hypot(expected_current.im);
                assert!(
                    error <= 2e-4 + 2e-6 * scale,
                    "{case} {short_name} {bus_name}.{terminal} current error {error:.3e} A"
                );
            }
        }
        let expected_power: Complex =
            expected
                .powers
                .iter()
                .fold(Complex { re: 0.0, im: 0.0 }, |sum, value| Complex {
                    re: sum.re + value.re,
                    im: sum.im + value.im,
                });
        let actual_power = actual_ports
            .iter()
            .fold(Complex { re: 0.0, im: 0.0 }, |sum, port| Complex {
                re: sum.re + port.power_into_element.re,
                im: sum.im + port.power_into_element.im,
            });
        let power_error =
            (actual_power.re - expected_power.re).hypot(actual_power.im - expected_power.im);
        let power_scale = expected_power.re.hypot(expected_power.im);
        assert!(
            power_error <= 2e-2 + 2e-6 * power_scale,
            "{case} {short_name} power error {power_error:.3e} VA"
        );
    }
    assert!(result
        .source_reactions
        .iter()
        .any(|reaction| reaction.power_into_network.re > 0.0));
    let source_power = result
        .source_reactions
        .iter()
        .map(|reaction| reaction.power_into_network)
        .fold(Complex { re: 0.0, im: 0.0 }, |sum, value| Complex {
            re: sum.re + value.re,
            im: sum.im + value.im,
        });
    let element_power = result
        .element_ports
        .iter()
        .map(|port| port.power_into_element)
        .fold(Complex { re: 0.0, im: 0.0 }, |sum, value| Complex {
            re: sum.re + value.re,
            im: sum.im + value.im,
        });
    assert!(
        (source_power.re - element_power.re).hypot(source_power.im - element_power.im)
            <= 1e-2 + 2e-6 * source_power.re.hypot(source_power.im),
        "{case} source/element complex-power balance: source=({:.6e},{:.6e}) element=({:.6e},{:.6e})",
        source_power.re,
        source_power.im,
        element_power.re,
        element_power.im
    );
}

fn actual_ports_are_finite(result: &McPfResult, element: &str) -> bool {
    result
        .element_ports
        .iter()
        .filter(|port| port.element == element)
        .all(|port| {
            port.current_into_element.re.is_finite()
                && port.current_into_element.im.is_finite()
                && port.power_into_element.re.is_finite()
                && port.power_into_element.im.is_finite()
        })
}

macro_rules! oracle_case {
    ($name:ident, $input:literal, $reference:literal) => {
        #[test]
        fn $name() {
            run(
                stringify!($name),
                include_str!($input),
                include_str!($reference),
            );
        }
    };
}

oracle_case!(
    pf_1ph_freeneutral,
    "data/mc_pf/oracle_inputs/pf_1ph_freeneutral.json",
    "data/mc_pf/oracle_refs/pf_1ph_freeneutral.json"
);
oracle_case!(
    pf_1ph_impedanceneutral,
    "data/mc_pf/oracle_inputs/pf_1ph_impedanceneutral.json",
    "data/mc_pf/oracle_refs/pf_1ph_impedanceneutral.json"
);
oracle_case!(
    pf_1ph_line,
    "data/mc_pf/oracle_inputs/pf_1ph_line.json",
    "data/mc_pf/oracle_refs/pf_1ph_line.json"
);
oracle_case!(
    pf_3ph_line,
    "data/mc_pf/oracle_inputs/pf_3ph_line.json",
    "data/mc_pf/oracle_refs/pf_3ph_line.json"
);
oracle_case!(
    pf_delta_load,
    "data/mc_pf/oracle_inputs/pf_delta_load.json",
    "data/mc_pf/oracle_refs/pf_delta_load.json"
);
oracle_case!(
    pf_dy_xfmr,
    "data/mc_pf/oracle_inputs/pf_dy_xfmr.json",
    "data/mc_pf/oracle_refs/pf_dy_xfmr.json"
);
oracle_case!(
    pf_dy_xfmr_rneut,
    "data/mc_pf/oracle_inputs/pf_dy_xfmr_rneut.json",
    "data/mc_pf/oracle_refs/pf_dy_xfmr_rneut.json"
);
oracle_case!(
    pf_dy_xfmr_tap,
    "data/mc_pf/oracle_inputs/pf_dy_xfmr_tap.json",
    "data/mc_pf/oracle_refs/pf_dy_xfmr_tap.json"
);
oracle_case!(
    pf_yd_xfmr,
    "data/mc_pf/oracle_inputs/pf_yd_xfmr.json",
    "data/mc_pf/oracle_refs/pf_yd_xfmr.json"
);
